# nixpacks.toml
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r backend/requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 120 app:app"