# nixpacks.toml
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:5000 --workers 4 --timeout 120"