"""Added company fields to Customer model

Revision ID: b66a4412985b
Revises: 
Create Date: 2025-10-19 18:41:45.986383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66a4412985b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(length=50), nullable=True))
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
        batch_op.drop_column('company_size')
        batch_op.drop_column('industry')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
