"""Add new schema dev A

Revision ID: 3561401439a9
Revises: 3fdb6c470743
Create Date: 2026-02-19 01:18:54.710383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3561401439a9'
down_revision = '3fdb6c470743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interior_appliance_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('energy_rating', sa.String(length=10), nullable=True),
    sa.Column('warranty_years', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low_tier_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mid_tier_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high_tier_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('interior_appliance_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_appliance_catalog_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('date_of_measure', sa.Date(), nullable=True),
    sa.Column('date_of_installation', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('salesperson', sa.String(length=200), nullable=True),
    sa.Column('assigned_team', sa.String(length=200), nullable=True),
    sa.Column('primary_fitter', sa.String(length=200), nullable=True),
    sa.Column('project_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interior_bedroom_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('bedside_cabinets', sa.Boolean(), nullable=True),
    sa.Column('dresser_desk', sa.Boolean(), nullable=True),
    sa.Column('internal_mirror', sa.Boolean(), nullable=True),
    sa.Column('mirror_type', sa.String(length=100), nullable=True),
    sa.Column('mirror_quantity', sa.Integer(), nullable=True),
    sa.Column('soffit_lights', sa.Boolean(), nullable=True),
    sa.Column('soffit_light_color', sa.String(length=50), nullable=True),
    sa.Column('soffit_light_quantity', sa.Integer(), nullable=True),
    sa.Column('gable_lights', sa.Boolean(), nullable=True),
    sa.Column('gable_light_color', sa.String(length=50), nullable=True),
    sa.Column('gable_light_quantity', sa.Integer(), nullable=True),
    sa.Column('accessories', sa.JSON(), nullable=True),
    sa.Column('floor_protection', sa.String(length=100), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_bedroom_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_bedroom_checklists_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('drawing_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_drawings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_drawings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_kitchen_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('appliances', sa.JSON(), nullable=True),
    sa.Column('worktop_features', sa.Text(), nullable=True),
    sa.Column('worktop_size', sa.String(length=100), nullable=True),
    sa.Column('under_lighting', sa.Boolean(), nullable=True),
    sa.Column('sink_details', sa.Text(), nullable=True),
    sa.Column('sink_customer_owned', sa.Boolean(), nullable=True),
    sa.Column('tap_details', sa.Text(), nullable=True),
    sa.Column('tap_customer_owned', sa.Boolean(), nullable=True),
    sa.Column('accessories', sa.JSON(), nullable=True),
    sa.Column('floor_protection', sa.String(length=100), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_kitchen_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_kitchen_checklists_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_material_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('material_description', sa.Text(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_material_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_material_orders_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('country_master', schema=None) as batch_op:
        batch_op.alter_column('country_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_country_master_country_name'), ['country_name'], unique=True)

    with op.batch_alter_table('currency_master', schema=None) as batch_op:
        batch_op.alter_column('currency_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_currency_master_currency_code'), ['currency_code'], unique=True)

    with op.batch_alter_table('designation_master', schema=None) as batch_op:
        batch_op.alter_column('designation_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['designation_description'])

    with op.batch_alter_table('employee_master', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('employee_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_employee_master_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_master_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant_master', ['tenant_id'], ['tenant_id'])

    with op.batch_alter_table('module_master', schema=None) as batch_op:
        batch_op.alter_column('module_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('module_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_module_master_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_master_module_code'), ['module_code'], unique=True)

    with op.batch_alter_table('permission_catalog', schema=None) as batch_op:
        batch_op.alter_column('permission_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_permission_catalog_permission_code'), ['permission_code'], unique=True)

    with op.batch_alter_table('role_master', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_role_master_role_name'), ['role_name'], unique=True)

    with op.batch_alter_table('role_permission_mapping', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('permission_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_role_permission_mapping_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permission_mapping_role_id'), ['role_id'], unique=False)
        batch_op.create_unique_constraint('uq_role_permission', ['role_id', 'permission_id'])

    with op.batch_alter_table('services_master', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('service_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('service_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index('idx_service_code_tenant', ['service_code', 'tenant_id'], unique=False)
        batch_op.create_index('idx_service_tenant_active', ['tenant_id', 'date_from', 'date_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_master_service_code'), ['service_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_master_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('stage_master', schema=None) as batch_op:
        batch_op.alter_column('stage_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('stage_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('subscription_module_mapping', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_subscription_module_mapping_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_module_mapping_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_unique_constraint('uq_subscription_module', ['subscription_id', 'module_id'])

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.alter_column('subscription_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('subscription_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_subscription_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_subscription_code'), ['subscription_code'], unique=True)

    with op.batch_alter_table('supplier_master', schema=None) as batch_op:
        batch_op.alter_column('supplier_company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_supplier_master_supplier_company_name'), ['supplier_company_name'], unique=False)

    with op.batch_alter_table('tenant_master', schema=None) as batch_op:
        batch_op.alter_column('tenant_company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_tenant_master_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_master_tenant_company_name'), ['tenant_company_name'], unique=False)

    with op.batch_alter_table('tenant_module_mapping', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_tenant_module_mapping_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_module_mapping_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_tenant_module', ['tenant_id', 'module_id'])

    with op.batch_alter_table('tenant_subscription', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('subscription_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_tenant_subscription_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_subscription_subscription_end_date'), ['subscription_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_subscription_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('uom_master', schema=None) as batch_op:
        batch_op.alter_column('uom_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['uom_description'])

    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_master_user_name'), ['user_name'], unique=True)
        batch_op.create_unique_constraint(None, ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_master_user_name'))
        batch_op.alter_column('updated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('uom_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('uom_description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tenant_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_subscription_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_subscription_subscription_end_date'))
        batch_op.drop_index(batch_op.f('ix_tenant_subscription_is_active'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('subscription_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('tenant_module_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenant_module', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tenant_module_mapping_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_module_mapping_module_id'))
        batch_op.alter_column('module_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.SMALLINT(),
               nullable=True)

    with op.batch_alter_table('tenant_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_master_tenant_company_name'))
        batch_op.drop_index(batch_op.f('ix_tenant_master_is_active'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('tenant_company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('supplier_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_master_supplier_company_name'))
        batch_op.alter_column('supplier_company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_subscription_code'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_is_active'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('subscription_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('subscription_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('subscription_module_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subscription_module', type_='unique')
        batch_op.drop_index(batch_op.f('ix_subscription_module_mapping_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_module_mapping_module_id'))
        batch_op.alter_column('module_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('subscription_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('stage_master', schema=None) as batch_op:
        batch_op.alter_column('stage_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('stage_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('services_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_master_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_services_master_service_code'))
        batch_op.drop_index('idx_service_tenant_active')
        batch_op.drop_index('idx_service_code_tenant')
        batch_op.alter_column('service_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('service_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.SMALLINT(),
               nullable=True)

    with op.batch_alter_table('role_permission_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_permission', type_='unique')
        batch_op.drop_index(batch_op.f('ix_role_permission_mapping_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permission_mapping_permission_id'))
        batch_op.alter_column('permission_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.SMALLINT(),
               nullable=True)

    with op.batch_alter_table('role_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_master_role_name'))
        batch_op.alter_column('role_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('role_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('permission_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_catalog_permission_code'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('permission_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('module_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_master_module_code'))
        batch_op.drop_index(batch_op.f('ix_module_master_is_active'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('module_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('module_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('employee_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_master_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_employee_master_email'))
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('employee_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('designation_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('designation_description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('currency_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_master_currency_code'))
        batch_op.alter_column('currency_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('currency_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('country_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_master_country_name'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('country_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('interior_material_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_material_orders_tenant_id'))

    op.drop_table('interior_material_orders')
    with op.batch_alter_table('interior_kitchen_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_kitchen_checklists_tenant_id'))

    op.drop_table('interior_kitchen_checklists')
    with op.batch_alter_table('interior_drawings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_drawings_tenant_id'))

    op.drop_table('interior_drawings')
    with op.batch_alter_table('interior_bedroom_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_bedroom_checklists_tenant_id'))

    op.drop_table('interior_bedroom_checklists')
    op.drop_table('interior_projects')
    with op.batch_alter_table('interior_appliance_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_appliance_catalog_tenant_id'))

    op.drop_table('interior_appliance_catalog')
    # ### end Alembic commands ###
