"""Add drawings and cutting_list tables

Revision ID: 3fdb6c470743
Revises: 
Create Date: 2026-01-20 09:58:28.307927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fdb6c470743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interior_appliance_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('energy_rating', sa.String(length=10), nullable=True),
    sa.Column('warranty_years', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low_tier_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mid_tier_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high_tier_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('interior_appliance_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_appliance_catalog_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('date_of_measure', sa.Date(), nullable=True),
    sa.Column('date_of_installation', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('salesperson', sa.String(length=200), nullable=True),
    sa.Column('assigned_team', sa.String(length=200), nullable=True),
    sa.Column('primary_fitter', sa.String(length=200), nullable=True),
    sa.Column('project_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('drawings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ocr_method', sa.String(length=50), nullable=True),
    sa.Column('raw_ocr_output', sa.Text(), nullable=True),
    sa.Column('optimization_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interior_bedroom_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('bedside_cabinets', sa.Boolean(), nullable=True),
    sa.Column('dresser_desk', sa.Boolean(), nullable=True),
    sa.Column('internal_mirror', sa.Boolean(), nullable=True),
    sa.Column('mirror_type', sa.String(length=100), nullable=True),
    sa.Column('mirror_quantity', sa.Integer(), nullable=True),
    sa.Column('soffit_lights', sa.Boolean(), nullable=True),
    sa.Column('soffit_light_color', sa.String(length=50), nullable=True),
    sa.Column('soffit_light_quantity', sa.Integer(), nullable=True),
    sa.Column('gable_lights', sa.Boolean(), nullable=True),
    sa.Column('gable_light_color', sa.String(length=50), nullable=True),
    sa.Column('gable_light_quantity', sa.Integer(), nullable=True),
    sa.Column('accessories', sa.JSON(), nullable=True),
    sa.Column('floor_protection', sa.String(length=100), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_bedroom_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_bedroom_checklists_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('drawing_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_drawings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_drawings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_kitchen_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('appliances', sa.JSON(), nullable=True),
    sa.Column('worktop_features', sa.Text(), nullable=True),
    sa.Column('worktop_size', sa.String(length=100), nullable=True),
    sa.Column('under_lighting', sa.Boolean(), nullable=True),
    sa.Column('sink_details', sa.Text(), nullable=True),
    sa.Column('sink_customer_owned', sa.Boolean(), nullable=True),
    sa.Column('tap_details', sa.Text(), nullable=True),
    sa.Column('tap_customer_owned', sa.Boolean(), nullable=True),
    sa.Column('accessories', sa.JSON(), nullable=True),
    sa.Column('floor_protection', sa.String(length=100), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_kitchen_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_kitchen_checklists_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('interior_material_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('material_description', sa.Text(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['interior_projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interior_material_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interior_material_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cutting_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drawing_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=True),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.Column('overall_unit_width', sa.Integer(), nullable=True),
    sa.Column('component_width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('material_thickness', sa.Integer(), nullable=True),
    sa.Column('edge_banding_notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_quote_line_items_quote_id'))

    op.drop_table('quote_line_items')
    with op.batch_alter_table('tenant_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tenant_domains_tenant_id'))

    op.drop_table('tenant_domains')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_quotes_customer_id'))
        batch_op.drop_index(batch_op.f('idx_quotes_opportunity_id'))
        batch_op.drop_index(batch_op.f('idx_quotes_tenant_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_activities_tenant'))
        batch_op.create_index(batch_op.f('ix_activities_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('activities_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('estimated_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_assignments_tenant'))
        batch_op.create_index(batch_op.f('ix_assignments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('create', 'update', 'delete', name='audit_action_enum'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_audit_logs_tenant'))
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('messages',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_chat_history_last_updated'))
        batch_op.drop_index(batch_op.f('idx_chat_history_user_id'))
        batch_op.create_index(batch_op.f('ix_chat_history_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_chat_history_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('conversation_history')
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('customer_form_data', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_customer_form_data_tenant'))
        batch_op.create_index(batch_op.f('ix_customer_form_data_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_customers_tenant'))
        batch_op.create_index(batch_op.f('ix_customers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_customers_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('job_workflow_stage')

    with op.batch_alter_table('data_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_data_imports_tenant'))
        batch_op.create_index(batch_op.f('ix_data_imports_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.alter_column('template_type',
               existing_type=postgresql.ENUM('Invoice', 'Receipt', 'Proposal', 'Contract', 'Agreement', 'Terms', 'Other', name='document_template_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_document_templates_tenant'))
        batch_op.create_index(batch_op.f('ix_document_templates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('education_certificates', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('certificate_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_certificates_customer'))
        batch_op.drop_index(batch_op.f('idx_certificates_tenant'))
        batch_op.create_index(batch_op.f('ix_education_certificates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('education_certificates_tenant_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_certificates_customer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_certificates_test_result_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'education_test_results', ['test_result_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('education_pti_forms', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('practical_assessment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_pti_forms_customer'))
        batch_op.drop_index(batch_op.f('idx_pti_forms_tenant'))
        batch_op.create_index(batch_op.f('ix_education_pti_forms_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('education_pti_forms_tenant_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_pti_forms_instructor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_pti_forms_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('education_test_results', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_test_results_customer'))
        batch_op.drop_index(batch_op.f('idx_test_results_tenant'))
        batch_op.drop_index(batch_op.f('idx_test_results_user'))
        batch_op.create_index(batch_op.f('ix_education_test_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_test_results_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('education_test_results_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_test_results_customer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_test_results_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('education_training_batches', schema=None) as batch_op:
        batch_op.alter_column('batch_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_training_batches_tenant'))
        batch_op.create_index(batch_op.f('ix_education_training_batches_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('education_training_batches_instructor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('education_training_batches_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_form_submissions_tenant'))
        batch_op.create_index(batch_op.f('ix_form_submissions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_invoice_line_items_tenant'))
        batch_op.create_index(batch_op.f('ix_invoice_line_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('invoice_line_items_invoice_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_invoices_tenant'))
        batch_op.drop_constraint(batch_op.f('invoices_invoice_number_tenant_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(None, ['invoice_number'])
        batch_op.drop_constraint(batch_op.f('fk_invoices_tenant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('invoices_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])
        batch_op.drop_column('payment_details')
        batch_op.drop_column('taxes')
        batch_op.drop_column('company_details')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('job_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('job_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'General'::text"))
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Prospect'::text"))
        batch_op.alter_column('priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Medium'::text"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('primary_contact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('team_members_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('quote_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_jobs_created_at'))
        batch_op.drop_index(batch_op.f('idx_jobs_customer_id'))
        batch_op.drop_index(batch_op.f('idx_jobs_due_date'))
        batch_op.drop_index(batch_op.f('idx_jobs_job_reference'))
        batch_op.drop_index(batch_op.f('idx_jobs_priority'))
        batch_op.drop_index(batch_op.f('idx_jobs_stage'))
        batch_op.drop_index(batch_op.f('idx_jobs_tenant'))
        batch_op.create_index(batch_op.f('ix_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('jobs_customer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_jobs_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Stores job/project information for the CRM system'
    )
        batch_op.drop_column('account_manager')

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_login_attempts_email'))
        batch_op.drop_index(batch_op.f('idx_login_attempts_tenant'))
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_login_attempts_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_opportunities_tenant'))
        batch_op.create_index(batch_op.f('ix_opportunities_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_opportunities_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('opportunity_documents', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_opportunity_documents_tenant'))
        batch_op.create_index(batch_op.f('ix_opportunity_documents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_opportunity_documents_tenant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('opportunity_documents_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('opportunity_notes', schema=None) as batch_op:
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_opportunity_notes_tenant'))
        batch_op.create_index(batch_op.f('ix_opportunity_notes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('opportunity_notes_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=postgresql.ENUM('Bank Transfer', 'Cash', 'Card', 'Check', 'Other', name='payment_method_enum'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Bank Transfer'::payment_method_enum"))
        batch_op.drop_index(batch_op.f('idx_payments_tenant'))
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_categories_tenant'))
        batch_op.create_index(batch_op.f('ix_product_categories_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_product_categories_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_products_tenant'))
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_products_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('proposal_items', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_proposal_items_tenant'))
        batch_op.create_index(batch_op.f('ix_proposal_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('proposal_items_proposal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proposals', ['proposal_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_index(batch_op.f('idx_proposals_tenant'))
        batch_op.create_index(batch_op.f('ix_proposals_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_proposals_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('salespeople', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_salespeople_tenant'))
        batch_op.create_index(batch_op.f('ix_salespeople_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_salespeople_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_team_members_tenant'))
        batch_op.create_index(batch_op.f('ix_team_members_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_team_members_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_teams_tenant'))
        batch_op.create_index(batch_op.f('ix_teams_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_teams_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('enabled_modules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('terminology',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('pipeline_stages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('custom_fields_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_tenants_stripe_customer'))
        batch_op.drop_index(batch_op.f('idx_tenants_stripe_subscription'))
        batch_op.drop_index(batch_op.f('idx_tenants_subscription_status'))
        batch_op.drop_constraint(batch_op.f('tenants_stripe_customer_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('tenants_stripe_subscription_id_key'), type_='unique')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_current_period_end')
        batch_op.drop_column('subscription_billing_cycle')

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_user_sessions_tenant'))
        batch_op.create_index(batch_op.f('ix_user_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_user_sessions_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_tenant'))
        batch_op.drop_index(batch_op.f('users_tenant_email_unique'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_email_tenant', ['email', 'tenant_id'])
        batch_op.drop_constraint(batch_op.f('fk_users_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('versioned_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_versioned_snapshots_tenant'))
        batch_op.drop_constraint(batch_op.f('versioned_snapshots_entity_type_entity_id_version_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_versioned_snapshots_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versioned_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_versioned_snapshots_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('versioned_snapshots_entity_type_entity_id_version_number_key'), ['entity_type', 'entity_id', 'version_number'])
        batch_op.create_index(batch_op.f('idx_versioned_snapshots_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_user_email_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('users_tenant_email_unique'), ['tenant_id', 'email'], unique=True)
        batch_op.create_index(batch_op.f('idx_users_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_sessions_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_user_sessions_tenant_id'))
        batch_op.create_index(batch_op.f('idx_user_sessions_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('session_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_billing_cycle', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(length=50), server_default=sa.text("'inactive'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('tenants_stripe_subscription_id_key'), ['stripe_subscription_id'])
        batch_op.create_unique_constraint(batch_op.f('tenants_stripe_customer_id_key'), ['stripe_customer_id'])
        batch_op.create_index(batch_op.f('idx_tenants_subscription_status'), ['subscription_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_tenants_stripe_subscription'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tenants_stripe_customer'), ['stripe_customer_id'], unique=False)
        batch_op.alter_column('settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('custom_fields_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('pipeline_stages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('terminology',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('enabled_modules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_teams_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_teams_tenant_id'))
        batch_op.create_index(batch_op.f('idx_teams_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_team_members_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_team_members_tenant_id'))
        batch_op.create_index(batch_op.f('idx_team_members_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('salespeople', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_salespeople_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_salespeople_tenant_id'))
        batch_op.create_index(batch_op.f('idx_salespeople_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_proposals_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_proposals_tenant_id'))
        batch_op.create_index(batch_op.f('idx_proposals_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('custom_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('proposal_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proposal_items_proposal_id_fkey'), 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_proposal_items_tenant_id'))
        batch_op.create_index(batch_op.f('idx_proposal_items_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_products_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))
        batch_op.create_index(batch_op.f('idx_products_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_product_categories_tenant_id'))
        batch_op.create_index(batch_op.f('idx_product_categories_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.create_index(batch_op.f('idx_payments_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('method',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Bank Transfer', 'Cash', 'Card', 'Check', 'Other', name='payment_method_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Bank Transfer'::payment_method_enum"))
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('opportunity_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('opportunity_notes_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_opportunity_notes_tenant_id'))
        batch_op.create_index(batch_op.f('idx_opportunity_notes_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('opportunity_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('opportunity_documents_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_opportunity_documents_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_opportunity_documents_tenant_id'))
        batch_op.create_index(batch_op.f('idx_opportunity_documents_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_opportunities_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_opportunities_tenant_id'))
        batch_op.create_index(batch_op.f('idx_opportunities_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('custom_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_login_attempts_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_login_attempts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.create_index(batch_op.f('idx_login_attempts_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_login_attempts_email'), ['email'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_manager', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Stores job/project information for the CRM system',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_jobs_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('jobs_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_jobs_tenant_id'))
        batch_op.create_index(batch_op.f('idx_jobs_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_job_reference'), ['job_reference'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('custom_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('quote_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('team_members_json',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('primary_contact',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Medium'::text"))
        batch_op.alter_column('stage',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Prospect'::text"))
        batch_op.alter_column('tags',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'General'::text"))
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('job_reference',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Snapshot of company details at invoice creation time'))
        batch_op.add_column(sa.Column('taxes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Array of tax objects: [{name, rate, amount}]'))
        batch_op.add_column(sa.Column('payment_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Snapshot of payment details at invoice creation time'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoices_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_invoices_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('invoices_invoice_number_tenant_key'), ['tenant_id', 'invoice_number'])
        batch_op.create_index(batch_op.f('idx_invoices_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('custom_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoice_line_items_invoice_id_fkey'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_tenant_id'))
        batch_op.create_index(batch_op.f('idx_invoice_line_items_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_form_submissions_tenant_id'))
        batch_op.create_index(batch_op.f('idx_form_submissions_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('education_training_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('education_training_batches_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('education_training_batches_instructor_id_fkey'), 'users', ['instructor_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_education_training_batches_tenant_id'))
        batch_op.create_index(batch_op.f('idx_training_batches_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('batch_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('education_test_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('education_test_results_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('education_test_results_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('education_test_results_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_education_test_results_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_education_test_results_id'))
        batch_op.create_index(batch_op.f('idx_test_results_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_results_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_results_customer'), ['customer_id'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('education_pti_forms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('education_pti_forms_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('education_pti_forms_instructor_id_fkey'), 'users', ['instructor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('education_pti_forms_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_education_pti_forms_tenant_id'))
        batch_op.create_index(batch_op.f('idx_pti_forms_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pti_forms_customer'), ['customer_id'], unique=False)
        batch_op.alter_column('practical_assessment',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('education_certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('education_certificates_test_result_id_fkey'), 'education_test_results', ['test_result_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('education_certificates_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('education_certificates_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_education_certificates_tenant_id'))
        batch_op.create_index(batch_op.f('idx_certificates_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_certificates_customer'), ['customer_id'], unique=False)
        batch_op.alter_column('certificate_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_templates_tenant_id'))
        batch_op.create_index(batch_op.f('idx_document_templates_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('template_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Invoice', 'Receipt', 'Proposal', 'Contract', 'Agreement', 'Terms', 'Other', name='document_template_type_enum'),
               existing_nullable=False)

    with op.batch_alter_table('data_imports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_data_imports_tenant_id'))
        batch_op.create_index(batch_op.f('idx_data_imports_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_workflow_stage', sa.TEXT(), server_default=sa.text("'New'::text"), autoincrement=False, nullable=True, comment='Job workflow stage for Closed Won customers (New, Assigned, In Progress, etc.)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_customers_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_customers_tenant_id'))
        batch_op.create_index(batch_op.f('idx_customers_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('custom_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('customer_form_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_form_data_tenant_id'))
        batch_op.create_index(batch_op.f('idx_customer_form_data_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('conversation_history', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chat_history_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_session_id'))
        batch_op.create_index(batch_op.f('idx_chat_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_history_last_updated'), [sa.literal_column('last_updated DESC')], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('messages',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('context')
        batch_op.drop_column('session_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.create_index(batch_op.f('idx_audit_logs_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('create', 'update', 'delete', name='audit_action_enum'),
               existing_nullable=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_tenant_id'))
        batch_op.create_index(batch_op.f('idx_assignments_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('estimated_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_opportunity_id_fkey'), 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_activities_tenant_id'))
        batch_op.create_index(batch_op.f('idx_activities_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('opportunity_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quotes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quote_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quote_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('vat_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('20.00'), autoincrement=False, nullable=False),
    sa.Column('vat_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('company_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Snapshot of company details at quote creation time'),
    sa.Column('payment_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Snapshot of payment details at quote creation time'),
    sa.Column('taxes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Array of tax objects: [{name, rate, amount}]'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='quotes_customer_id_fkey'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name='quotes_opportunity_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quotes_pkey'),
    sa.UniqueConstraint('tenant_id', 'quote_number', name='quotes_quote_number_tenant_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quotes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_quotes_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_quotes_customer_id'), ['customer_id'], unique=False)

    op.create_table('tenant_domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_domains_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_domains_pkey')),
    sa.UniqueConstraint('domain', name=op.f('tenant_domains_domain_key')),
    sa.UniqueConstraint('domain', name=op.f('tenant_domains_domain_unique'))
    )
    with op.batch_alter_table('tenant_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tenant_domains_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quote_line_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('quote_line_items_quote_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_line_items_pkey'))
    )
    with op.batch_alter_table('quote_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quote_line_items_quote_id'), ['quote_id'], unique=False)

    op.drop_table('cutting_lists')
    with op.batch_alter_table('interior_material_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_material_orders_tenant_id'))

    op.drop_table('interior_material_orders')
    with op.batch_alter_table('interior_kitchen_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_kitchen_checklists_tenant_id'))

    op.drop_table('interior_kitchen_checklists')
    with op.batch_alter_table('interior_drawings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_drawings_tenant_id'))

    op.drop_table('interior_drawings')
    with op.batch_alter_table('interior_bedroom_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_bedroom_checklists_tenant_id'))

    op.drop_table('interior_bedroom_checklists')
    op.drop_table('drawings')
    with op.batch_alter_table('interior_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_projects_tenant_id'))

    op.drop_table('interior_projects')
    with op.batch_alter_table('interior_appliance_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interior_appliance_catalog_tenant_id'))

    op.drop_table('interior_appliance_catalog')
    # ### end Alembic commands ###
